name: Deploy Flask to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Navigate to app directory
          cd /
          # Pull latest changes from GitHub
          git pull
          # Install dependencies (if any changes)
          source venv/bin/activate
          pip install -r requirements.txt
          # Restart the application service (e.g., Gunicorn via systemd)
          sudo systemctl restart backend_dusan.service
          # Check service status (optional)
          sudo systemctl status backend_dusan.service
